server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  devLogger:
    path: "logs/dev"
    file: "{Y-m-d}[dev].log"
    rotateExpire: 86400000
    level: "dev"
    stdout: true
    stdoutColorDisabled: false
    writerColorEnable: true
  prodLogger:
    path: "logs/prod"
    file: "{Y-m-d}[prod].log"
    rotateExpire: 86400000
    level: "prod"
    stdout: false
    stdoutColorDisabled: false
    writerColorEnable: true

gfcli:
  gen:
    dao:
      - link:     "mysql:root:root@tcp(192.168.1.104:3306)/gogf"
        tables:   "user,product,order"
        jsonCase: "CamelLower"

database:
  default:
    type:  "mysql"
    host:  "192.168.1.104"
    port:  "3306"
    user: "root"
    pass: "root"
    maxOpen: "3"
    maxIdle: "1"
    debug: true
    name: "gogf"
  logger:
    path:    "logs/mysql"
    level:   "all"
    stdout:  false