// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"mygogf/internal/service/internal/dao/internal"
)

// orderDao is the data access object for table order.
// You can define custom methods on it to extend its functionality as you wish.
type orderDao struct {
	*internal.OrderDao
}

var (
	// Order is globally public accessible object for table order operations.
	Order = orderDao{
		internal.NewOrderDao(),
	}
)

// Fill with you ideas below.
