// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-01 23:40:34
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Order is the golang structure of table order for DAO operations like Where/Data.
type Order struct {
	g.Meta      `orm:"table:order, do:true"`
	Id          interface{} // 主键id
	OrderId     interface{} // 订单号
	Count       interface{} // 商品数量
	ProductName interface{} // 商品名称
	Status      interface{} // 订单状态
	CreateAt    *gtime.Time // 订单创建时间
}
