// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-01 23:40:34
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Product is the golang structure of table product for DAO operations like Where/Data.
type Product struct {
	g.Meta   `orm:"table:product, do:true"`
	Id       interface{} // 主键id
	Name     interface{} // 商品名称
	Price    interface{} // 商品价格
	Count    interface{} // 商品数量
	CreateAt *gtime.Time // 创建时间
	UpdateAt *gtime.Time // 修改时间
}
