// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-01 23:40:34
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Order is the golang structure for table order.
type Order struct {
	Id          uint        `json:"id"          ` // 主键id
	OrderId     string      `json:"orderId"     ` // 订单号
	Count       string      `json:"count"       ` // 商品数量
	ProductName string      `json:"productName" ` // 商品名称
	Status      string      `json:"status"      ` // 订单状态
	CreateAt    *gtime.Time `json:"createAt"    ` // 订单创建时间
}
