// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-01 23:40:34
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Product is the golang structure for table product.
type Product struct {
	Id       uint        `json:"id"       ` // 主键id
	Name     string      `json:"name"     ` // 商品名称
	Price    int         `json:"price"    ` // 商品价格
	Count    int         `json:"count"    ` // 商品数量
	CreateAt *gtime.Time `json:"createAt" ` // 创建时间
	UpdateAt *gtime.Time `json:"updateAt" ` // 修改时间
}
