// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-02-01 23:40:34
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id       uint64      `json:"id" p:"id"       `                                                  // User ID
	Passport string      `json:"passport" p:"passport" v:"required|length:6,15#请输入账户|账户长度最小为6,最大为15"` // User Passport
	Password string      `json:"password" p:"password" v:"required|length:10,10#请输入密码|账户长度为10"`          // User Password
	Nickname string      `json:"nickname" p:"nickname" v:"required"`                                       // User Nickname
	CreateAt *gtime.Time `json:"create_at" p:"create_at" `                                                   // Created Time
	UpdateAt *gtime.Time `json:"update_at" p:"update_at" `                                                   // Updated Time
}
